name: Docker Image CI

on: [push]

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    
    - uses: actions/checkout@v1
    - name: Build
      run: docker build . --file RazzleServer/Dockerfile --tag docker.pkg.github.com/razfriman/razzleserver/razzle-server:latest
    - name: Login
      env:
        REGISTRY_TOKEN: ${{ secrets.REGISTRY_TOKEN }}
      run: docker login docker.pkg.github.com -u razfriman -p $REGISTRY_TOKEN
    - name: Push
      run: docker push docker.pkg.github.com/razfriman/razzleserver/razzle-server:latest
      

