name: Docker Image CI

on: [push]

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: docker build . --file RazzleServer/Dockerfile --tag docker.pkg.github.com/razfriman/razzleserver/razzle-server:latest
    - name: Push
      run: docker push docker.pkg.github.com/razfriman/razzleserver/razzle-server:latest
      

